# ----------------------------------------------------
# Code configuration
# If set via CLI, it will override this configuration)
# ----------------------------------------------------

# LLM used in summarization
llm:
  model: model-to-use 
  api_key: your-api-key
  base_url: your-model-provider-url

# How many hours going back (0 = all)
hours_lookback: 0

# How many articles per feed (0 = all)
max_articles_per_feed: 0

# Parallelization workers
max_workers: 8

# Output directory
output_dir: ./newspaper

# Telegram options
telegram:
  bot_token: your-chatbot-token
  chat_id: your-chatbot-chat-id

# -----------------------
# RSS Feed configuration
# -----------------------

# You must provide an URL from where fetch the feed, and the interests related to that URL
# Interests are user-generated. You can have how many interests you want per URL, just make sure every interest occupies one line
# The system will group articles based on their interests, so please ensure there are no typos
# As for the URL, you can use any RSS/Atom valid URL. 
# This means you are not block on just news RSS, but for example you can provide:
# YouTube: every channel provides a feed: 'https://www.youtube.com/feeds/videos.xml?channel_id=CHANNEL_ID'
# Reddit: every subreddit has its own feed: 'https://www.reddit.com/r/SUBREDDIT/.rss'
# Other websites: you can use tools like https://rsshub.app/ to generate feed from any site.

feeds:
  - https://feeds.bbci.co.uk/news/world/rss.xml
  - https://rss.nytimes.com/services/xml/rss/nyt/World.xml